version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_forward_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uv run python -m app.main
